#version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: intraservice-app
    restart: unless-stopped
    ports:
      - "${APP_PORT}:${APP_CONTAINER_PORT}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS='${DB_PASS}'
      - IntraServiceUrl=${INTRA_SERVICE_URL}
      - AgentUrl=${AGENT_URL}
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - FORWARDED_ALLOW_IPS=*
    networks:
      - app-network

  app-agent:
    build:
      context: .
      dockerfile: app-agent/Dockerfile
    container_name: intraservice-agent
    restart: unless-stopped
    ports:
      - "${AGENT_PORT}:${AGENT_CONTAINER_PORT}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS='${DB_PASS}'
      - IntraServiceUrl=${INTRA_SERVICE_URL}
      - AgentUrl=${AGENT_URL}

      #- ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - FORWARDED_ALLOW_IPS=*
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
