# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    environment: start

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from Environment
        run: |
          {
          echo "# Секреты из Environment (не логируются)"
          echo "DB_HOST=${{ secrets.DB_HOST }}"
          echo "DB_NAME=${{ secrets.DB_NAME }}"
          echo "DB_PASS=${{ secrets.DB_PASSWORD }}"
          echo "DB_USER=${{ secrets.DB_USER }}"

          echo "# Переменные из Environment"
          echo "AGENT_CONTAINER_PORT=${{ vars.AGENT_CONTAINER_PORT }}"
          echo "AGENT_PORT=${{ vars.AGENT_PORT }}"
          echo "AGENT_URL=${{ vars.AGENT_URL }}"
          echo "APP_CONTAINER_PORT=${{ vars.APP_CONTAINER_PORT }}"
          echo "APP_PORT=${{ vars.APP_PORT }}"
          echo "DB_PORT=${{ vars.DB_PORT }}"
          echo "INTRA_SERVICE_URL=${{ vars.INTRA_SERVICE_URL }}"
          } > .env

      # Runs a single command using the runners shell
      - name: Deploy with docker compose
        run: |
          docker compose --env-file .env up -d --build
      
      # Health checks 
      - name: Health checks
        run: |
          echo "🏥 Performing health checks..."
          
          # Даем время контейнерам запуститься
          sleep 15
          
          # Проверяем статус контейнеров
          docker compose ps
          
          # Проверяем логи контейнера app
          docker compose logs app --tail=20

          # Проверяем логи контейнера app-agent
          docker compose logs app-agent --tail=20
          
          docker compose exec app cat appsettings.json